# Site settings
title: home
description: My professional portfolio
permalink: /:title/ # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {file: "portfolio.md"}
  - {file: "resume.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:andrewjgreenwood81@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/andrewjgreenwood81"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/agreenwoodgamedev"}

# Build settings
markdown: kramdown
remote_theme: minima
theme: minima
plugins:
  - jekyll-feed
  - jekyll-plugins
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
